services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    ports:
      - 1433:1433
    environment:
      TZ: Asia/Tokyo
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Passw0rd
      MSSQL_PID: Express
      MSSQL_LCID: 1041
      MSSQL_COLLATION: Japanese_CI_AS
    volumes:
      - /storage/mssql/data:/var/opt/mssql/data
    restart: unless-stopped
