- name: Install nginx
  apt:
    name: nginx

- name: Copy SSL certificate
  copy:
    src: files/daieihawks.crt
    dest: /etc/ssl/certs/daieihawks.crt

- name: Copy SSL private key
  copy:
    src: files/daieihawks.key
    dest: /etc/ssl/private/daieihawks.key
    mode: "0600"

- name: Create nginx configuration
  copy:
    dest: /etc/nginx/nginx.conf
    content: |
      user www-data;
      worker_processes auto;
      pid /run/nginx.pid;

      events {
          worker_connections 1024;
      }

      http {
          include /etc/nginx/mime.types;
          default_type application/octet-stream;

          sendfile on;
          keepalive_timeout 65;
          client_max_body_size 500M;

          ssl_prefer_server_ciphers on;
          ssl_protocols TLSv1.2 TLSv1.3;
          ssl_certificate /etc/ssl/certs/daieihawks.crt;
          ssl_certificate_key /etc/ssl/private/daieihawks.key;

          proxy_set_header Host $http_host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-Proto https;
          proxy_set_header X-Forwarded-Host $host;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

          server {
              listen 443 ssl;
              server_name daieihawks;

              location / {
                  proxy_pass http://localhost;
              }
          }

          server {
              listen 443 ssl;
              server_name redmine.daieihawks;

              location / {
                  proxy_pass http://localhost:3000;
              }
          }

          server {
              listen 443 ssl;
              server_name gitea.daieihawks;

              location / {
                  proxy_pass http://localhost:3001;
              }
          }

          server {
              listen 443 ssl;
              server_name mopidy.daieihawks;

              location = / {
                  return 301 /iris/;
              }

              location / {
                  proxy_pass http://localhost:6680;

                  proxy_http_version 1.1;
                  proxy_set_header Host $http_host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-Proto https;
                  proxy_set_header X-Forwarded-Host $host;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header Upgrade $http_upgrade;
                  proxy_set_header Connection "upgrade";
              }
          }

          server {
              listen 443 ssl;
              server_name netdata.daieihawks;

              location / {
                  proxy_pass http://localhost:19999;
              }
          }
      }

- name: Enable and restart service
  systemd:
    name: nginx
    state: restarted
    enabled: yes
